spring:
    datasource:
        url: jdbc:mysql://localhost:3306/monopoly_mysql?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
